"""
pin_embed.py - (re)generate requirements-embed.txt, the hash-locked package
set for the embeddable Python that ships beside the Assistant exe.

    python pin_embed.py            # resolve TOP_LEVEL for cp312/win_amd64, write the file
    python pin_embed.py --check    # exit 1 if the file is missing or not hash-locked

Every wheel the resolver picks (top-level AND transitive) is downloaded once,
hashed with SHA-256, and written as  name==version --hash=sha256:...  so that
Build-Assistant.ps1 can install with  --require-hashes --only-binary=:all:
and pip refuses anything that is not byte-for-byte what was pinned here.
"""
import glob
import hashlib
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "requirements-embed.txt")
WHEELS = os.path.join(HERE, "cache", "wheels")

# What the skill's Python tools import. Versions match requirements-build.txt
# (the same libraries are frozen into the PDF Fixer) so both apps run the code
# that the tests and the engine selftest were run against.
TOP_LEVEL = [
    "python-pptx==1.0.2", "python-docx==1.2.0", "pypdf==6.14.2",
    "pymupdf==1.28.2", "pikepdf==10.12.0", "lxml==6.1.1",
    "fonttools==4.63.0", "pillow==12.3.0",
]
TARGET = ["--only-binary=:all:", "--platform", "win_amd64",
          "--python-version", "3.12", "--implementation", "cp", "--abi", "cp312"]

HEADER = """\
# Packages installed into the embeddable Python that ships beside the
# Assistant exe (Build-Assistant.ps1). Every line is pinned AND hashed:
# pip refuses anything that does not match, so a changed upstream wheel
# cannot enter the installer silently. Generated by pin_embed.py - edit
# TOP_LEVEL there and re-run it; do not hand-edit this file.
--only-binary=:all:
"""


def generate():
    shutil.rmtree(WHEELS, ignore_errors=True)
    os.makedirs(WHEELS)
    cmd = [sys.executable, "-m", "pip", "download", "-q", "-d", WHEELS] + TARGET + TOP_LEVEL
    subprocess.run(cmd, check=True)
    lines = [HEADER]
    for w in sorted(glob.glob(os.path.join(WHEELS, "*.whl"))):
        name = os.path.basename(w)
        dist, ver = name.split("-")[0].replace("_", "-"), name.split("-")[1]
        with open(w, "rb") as f:
            digest = hashlib.sha256(f.read()).hexdigest()
        lines.append("%s==%s \\\n    --hash=sha256:%s" % (dist, ver, digest))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d wheels)" % (OUT, len(lines) - 1))


def check():
    if not os.path.isfile(OUT):
        print("requirements-embed.txt is missing - run pin_embed.py")
        return 1
    txt = open(OUT, encoding="utf-8").read()
    pins = [ln for ln in txt.splitlines() if "==" in ln and not ln.startswith("#")]
    hashes = txt.count("--hash=sha256:")
    if not pins or hashes != len(pins):
        print("requirements-embed.txt is not fully hash-locked (%d pins, %d hashes)"
              % (len(pins), hashes))
        return 1
    print("requirements-embed.txt: %d hash-locked pins" % len(pins))
    return 0


if __name__ == "__main__":
    sys.exit(check() if "--check" in sys.argv else generate())
